# Generated by Django 3.2.18 on 2023-03-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_comment_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='posted_by',
            field=models.CharField(default='abhaycheck', max_length=100),
            preserve_default=False,
        ),
    ]
